ci: Add sccache
We use the embedded debug information for MSVC, because we ran into this error message in our windows CI:
```
FAILED: 3rdparty/fmt/CMakeFiles/fmt.dir/src/os.cc.obj
sccache C:\PROGRA~1\MICROS~2\2022\ENTERP~1\VC\Tools\MSVC\1440~1.338\bin\Hostx64\x64\cl.exe  /nologo /TP -DKNUT_BUILDDATE=\"2024-06-07\" -DKNUT_VERSION=\"1.0\" -DKNUT_VERSION_STRING="\"1.0 (revision: c91adac)\"" -DTEST_DATA_PATH=\"D:/a/knut/knut/test_data\" -ID:\a\knut\knut\build-ci\3rdparty\fmt -ID:\a\knut\knut\3rdparty\fmt -ID:\a\knut\knut\build-ci\3rdparty\fmt\fmt_autogen\include -ID:\a\knut\knut\3rdparty\fmt\include /DWIN32 /D_WINDOWS /GR /EHsc /Zi /O2 /Ob1 /DNDEBUG -std:c++latest -MD /showIncludes /Fo3rdparty\fmt\CMakeFiles\fmt.dir\src\os.cc.obj /Fdfmt.pdb /FS -c D:\a\knut\knut\3rdparty\fmt\src\os.cc
D:\a\knut\knut\3rdparty\fmt\src\os.cc: fatal error C1041: cannot open program database 'D:\a\knut\knut\build-ci\fmt.pdb'; if multiple CL.EXE write to the same .PDB file, please use /FS
```
Obviously /FS won't help, as that's already added.

However, in this issue: https://gitlab.kitware.com/cmake/cmake/-/issues/20222,
@mwestphal suggests that /Zi may be the issue. This makes sense, as
that's what's forcing the use of a separate pdb file for debug info.

If we use the Embedded format, this should fall back to /Z7, which
includes the debug information within the object files themselves.
So there should be no pdb file that can have lock contention.